### ISSUE TITLE
POST http://domain.tld/api/articles` resulted in a `400 Bad Request / {"success":false,"message":"Invalid method or invalid json string."}

### ISSUE THREAD

**Issue by bd8** [LeadCommerceDE/shopware-sdk#13]
Hallo,

ich hoffe ich kann hier deutsch schreiben.

Wenn ich einen neuen Artikel erstellen will kommt dieser Fehler. 
Ansicht funktioniert der Client, holen kann ich alles.

Per Postman kann ich ohne Probleme eine Artikel erstellen.

Woran könnte das liegen?

        $article = new Article();
        $article->setName("John product doe");
        $article->setDescription("Lorem ipsum");
        $article->setTaxId(19);
        $article->setMainDetailId('tkskl');

        $client->getArticleQuery()->create($article);

Bißchen dürftig die Informationen aber vielleicht habt ihr einen Tipp.
SW 5.2.12

**Comment by bd8** [comment]
Das selbe put / Update..

**Comment by amahrt** [comment]
Hallo @bd8, ich schaue mir das demnächst einmal an, vielen dank für deine Info.

**Comment by bd8** [comment]
Danke, mit der Client Klasse von Shopware klappts.

**Comment by marvinschroeder** [comment]
Dasselbe Problem..

**Comment by amahrt** [comment]
#14

**Comment by amahrt** [comment]
Müsste jetzt klappen; man muss allerdings ein paar mehr Werte angeben als nur die in dem Beispiel :)
